### ISSUE TITLE
(NFSU2) regarding Global Neon Support and Global Shadow Support

### ISSUE THREAD

**Issue by Zergei** [AeroWidescreen/NFSHDContentSupport#2]
is there any mod or guide in how to do it? i want to add a neon texture to be used in all cars but i think it may create a conflict with the game

this is the stuff i want to use 
https://www.mixmods.com.br/2015/09/nfsu2-neon-fix-correcao-das-bordas-do.html

**Comment by Zergei** [comment]
> You add a texture called "HD_NEON" to GlobalB.lzc. Then you enable GlobalNeon in the config file.
> 
> As for adding the texture, you should do this with Binary. **_Do not use NFS-TexEd_** because it doesn't allow you to control specific settings that need to be changed for the neon to render correctly, and it's known to break the GlobalB archive.
> 
> Make sure the Secondary settings of your new Neon texture uses the same settings as the original Neon texture: Rendering Order, AlphaBlendType, etc.
> 
> ![Binary](https://camo.githubusercontent.com/a4b020ff4ef617cd494af53ed216003353048144fd1286bc053181660581e8de/68747470733a2f2f692e696d6775722e636f6d2f74433248706d362e706e67)
> 
> Save and you should be good to go.

ok ty looks really complex but ill try

**Comment by Zergei** [comment]
ok sorry for keep asking but the thing is there 2 textures for the neon which should use for the "HD Neon" one?

[https://i.imgur.com/cHUa0jq.png](url)

**Comment by AeroWidescreen** [comment]
Use Neon DXT3, I guess? You only need one of them.
