### ISSUE TITLE
v1.2 NTSC speed2.exe

### ISSUE THREAD

**Issue by stertingen** [AeroWidescreen/NFSHDContentSupport#3]
On startup, I get the following message (same for the HD reflections mod):
```
This .exe is not supported.
Please use v1.2 NTSC speed2.exe (4,57 MB (4.800.512 bytes)).
```
So I guess my version is incompatible with HD content although I've patched the game to version 1.2; the speed.exe has a size of 5,70 MB (5.987.980 bytes).

What is the reason for this explicit version check (Like hard-coded memory locations)?

Can I help somehow providing support for my NFSU2 version? (How do I even get my version of NFSU2?)
Alternatively, where can the NTSC version be obtained?

**Comment by AeroWidescreen** [comment]
> What is the reason for this explicit version check (Like hard-coded memory locations)?

Yes.

> Can I help somehow providing support for my NFSU2 version? (How do I even get my version of NFSU2?)

You likely just need a no-cd exe. [HOODLUM v1.2](https://mega.nz/file/NSoSGIDJ#KmBdM1cmbGTaGQoxEhNm4-TKPDErcWF-Vms3ZlpDrf0) is the community standard, and it's what you're going to need if you plan on installing other scripts like Extra Options or Unlimiter. It's also what I personally use.

Backup your original exe before replacing it.

**Comment by ManiaWorks** [comment]
> 

The file you sent is expired, can you provide a new one?
